footnoteReturnLinkContents = "↩"
title = "Noetic Nought"
description = "Punch's home on the web"
enableRobotsTXT = true
languageCode = "en-US"
baseurl = "https://punchagan.muse-amuse.in/"
theme = "er"
rssLimit = 25
canonifyURLs = true
copyright = "© 2006-2026 CC-BY-SA-4.0"
# pygments
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "emacs"

[pagination]
pagerSize = 500

[markup.goldmark.renderer]
unsafe= true

[menu]
[[menu.main]]
identifier = "recurse-center"
name = "recurse-center"
title = "recurse-center"
url = "/recurse-center/"
weight = 10

[Params]
mainSections = ["blog"]
dateform = "Jan 2, 2006"
webmentiondateform = "15:04:05, Jan 2 2006"
twitter = "punchagan"
github = "punchagan"
email = "punchagan+blog@muse-amuse.in"
[Params.author]
name = "punchagan"
nick = "punchagan"
